name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  # ---------- BUILD ----------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🐳 Сборка тестового контейнера
        run: |
          docker build -t selenium-tests .
          docker save selenium-tests -o selenium-tests.tar

      - name: 📦 Сохранение артефактов (docker image)
        uses: actions/upload-artifact@v3
        with:
          name: selenium-tests
          path: selenium-tests.tar

  # ---------- TEST ----------
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: 📥 Загрузка docker image
        uses: actions/download-artifact@v3
        with:
          name: selenium-tests
          path: .

      - name: ▶ Запуск Selenium-тестов
        run: |
          mkdir -p allure-results
          docker load -i selenium-tests.tar
          docker run --rm -v ${{ github.workspace }}/allure-results:/allure-results selenium-tests

      - name: 📦 Сохранение артефактов (allure results)
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

  # ---------- REPORT ----------
  allure-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: 📥 Загрузка allure results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: ⚙ Установка Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz

      - name: 📊 Генерация Allure-отчета
        run: |
          ./allure-2.27.0/bin/allure generate allure-results --clean -o public

      - name: 📦 Сохранение артефактов (отчет)
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: public

  # ---------- DEPLOY ----------
  deploy:
    runs-on: ubuntu-latest
    needs: allure-report
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: public

      - name: 📤 Публикация на GitHub Pages
        uses: actions/upload-pages-artifact@v2

  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4